#!/usr/bin/env python3
"""Export each service's OpenAPI contract to contracts/openapi/<service>.yaml.

The contracts are generated from the running code so they can never drift from it; CI checks
that the committed files are current (``--check``). Each contract documents the privacy headers
every sensitive endpoint requires.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

PRIVACY_HEADERS = {
    "X-Purpose": "Registered purpose (catalog/purposes.yaml). Required on sensitive endpoints.",
    "X-Program": "Program the request is made for (see catalog/programs.yaml).",
    "X-Correlation-ID": "Correlation id propagated to downstream calls and audit events.",
    "X-Channel": "Access channel (api, portal, assisted, mobile).",
    "X-Device-Trust": "Device/session trust asserted by the access layer: low, managed or high.",
    "X-Case-ID": "Case the actor is working on; required by case-scoped purposes.",
    "X-Break-Glass-Grant": "Active break-glass grant id for the emergency_protection purpose.",
}

RESPONSE_HEADERS = {
    "X-Decision-ID": "Policy decision id recorded in the audit store.",
    "X-Policy-Version": "Catalogue/policy version used for the decision.",
    "X-Obligations": "Comma-separated obligations the caller must honour, e.g. no_export.",
}


def export(service: str) -> str:
    from pbd_spmis.app import service_app

    app = service_app(service)
    spec = app.openapi()
    spec.setdefault("components", {}).setdefault("securitySchemes", {})["bearerAuth"] = {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Service or user token. Development tokens are HS256; production uses OIDC.",
    }
    spec["security"] = [{"bearerAuth": []}]
    params = spec["components"].setdefault("parameters", {})
    for name, desc in PRIVACY_HEADERS.items():
        params[name.replace("-", "")] = {
            "name": name,
            "in": "header",
            "required": False,
            "schema": {"type": "string"},
            "description": desc,
        }
    headers = spec["components"].setdefault("headers", {})
    for name, desc in RESPONSE_HEADERS.items():
        headers[name] = {"schema": {"type": "string"}, "description": desc}
    spec["info"]["x-privacy-headers"] = list(PRIVACY_HEADERS)
    spec["info"]["x-response-headers"] = list(RESPONSE_HEADERS)
    spec["info"]["x-source"] = "generated by scripts/export_contracts.py; do not edit by hand"
    return yaml.safe_dump(spec, sort_keys=False, allow_unicode=True)


def main(argv: list[str]) -> int:
    from pbd_spmis.config import SERVICES

    out_dir = ROOT / "contracts" / "openapi"
    out_dir.mkdir(parents=True, exist_ok=True)
    stale = []
    for service in SERVICES:
        text = export(service)
        path = out_dir / f"{service}.yaml"
        if "--check" in argv:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(f"stale contracts: {stale}; run scripts/export_contracts.py", file=sys.stderr)
        return 1
    if "--check" in argv:
        print("contracts are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
